# Generated by Django 4.1.7 on 2023-02-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributename',
            name='kod',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='nazev',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='hodnota',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='nazev',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='nazev',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nazev',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='nazev',
            field=models.CharField(max_length=150),
        ),
    ]
